version: '3.7'

services:
    l0:
        build:
            context: .
            dockerfile: Dockerfile-compose
        command: [ 'make', 'start' ]
        volumes:
            - .:/usr/src/app
        environment:
            PORT: 80
        networks:
            - api_net

networks:
    api_net:
        external: true
